spring:
  mvc:
    servlet:
      path: /api/v1
    async:
      request-timeout: 3000000

  application:
    name: backend

  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/soltravel?serverTimezone=Asia/Seoul&useUniCode=yes&characterEncoding=UTF-8
    username: root
    password: thfxmfpqmf225!@
    hikari:
      pool-name: hikari-pool
      maximum-pool-size: 50
      minimum-idle: 50
      connection-timeout: 5000
      connection-init-sql: SELECT 1
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true

  sql:
    init:
      mode: always
  data:
    redis:
      host: redis
      port: 6379

  # Flyway 설정
  flyway:
    enabled: true
    locations: classpath:db/
    baseline-on-migrate: true



  # JPA 설정  
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        default_batch_fetch_size: 100 #fetch join 후 지연로딩하는 entity을 in 절로 미리 영속성 컨텍스트에 저장

  # Multipart File 설정
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 10MB


# Log 출력 설정
logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: debug
        type: trace

# JWT 설정
jwt:
  secret: { JWT_SECRET_KEY }
  expiration-time: 108000000

# 프론트엔드 프로젝트 관련 환경 변수
server:
  front:
    url: http://localhost:3000

  servlet:
    session:
      timeout: 30m

# S3 설정
cloud:
  aws:
    s3:
      bucket: my-s3-mingyu
    stack:
      auto: false
    region:
      static: ap-southeast-2
