spring:
  application:
    name: backend
    
  # JPA 설정  
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        default_batch_fetch_size: 100 #fetch join 후 지연로딩하는 entity을 in 절로 미리 영속성 컨텍스트에 저장

  # 소셜 로그인 설정
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: google-client-id
            client-secret: google-client-secret

# Log 출력 설정
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace


# 카카오, 네이버 api key
social:
  client:
    kakao:
      grant-type: authorization_code
      grant-type-refresh: refresh_token
      client-id: ce44932597263b3c038f3e226f3c3328
      redirect-uri: https://i11d104.p.ssafy.io/user/auth/login/kakao
      client-secret: VGCitmfgTmn+t2ou+zVxu6OA7TYNSAApWRexee/pjXA=
    naver:
      grant-type: authorization_code
      grant-type-refresh: refresh_token
      client_id: BUvsmsuF11bb6Ac_YdEh
      redirect-uri: https://i11d104.p.ssafy.io/user/auth/login/naver
      client_secret: agzrMxlQfB