spring:
  application:
    name: backend
    
  # JPA 설정  
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        default_batch_fetch_size: 100 #fetch join 후 지연로딩하는 entity을 in 절로 미리 영속성 컨텍스트에 저장

  # 소셜 로그인 설정
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: google-client-id
            client-secret: google-client-secret

# Log 출력 설정
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace


# 카카오, 네이버 api key
social:
  client:
    kakao:
      grant-type: authorization_code
      grant-type-refresh: refresh_token
      client-id: id
      redirect-uri: re
      client-secret: cs
    naver:
      grant-type: authorization_code
      grant-type-refresh: refresh_token
      client_id: id
      redirect-uri: re
      client_secret: cs